[package]
name = "capswiz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
clap = { version = "3.0.13", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.14"
rand = "0.8.4"
